# Generated by Django 6.0.6 on 2026-06-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('bed_no', models.IntegerField()),
                ('ip_number', models.IntegerField()),
                ('Signature', models.CharField(blank=True, max_length=50)),
                ('hospital_sanitaion', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('care_co_opp_of_administrator', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('promptness_of_service', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('doctor_response', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('satisfied_with_doctor_explanation', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('satisfied_by_nurse_service', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('if_no_specify_reason', models.TextField(blank=True, null=True)),
                ('ward_cleanliness', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('service_promptness_emegency_service', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('arrival_of_ambulance', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('satisfaction_with_ambulance_internal_service', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('pharmacy', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('x_ray_usg_echo_pathology_endoscopy_physio', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('ICU_OT', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')])),
                ('problem_during_stay', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('if_yes_specify_reason', models.TextField(blank=True, null=True)),
                ('if_yes_problem_solved_promptly_or_not', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('satisfied_with_overall_aspect_of_hospital', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('sharing_with_friend_if_yes', models.TextField(blank=True, null=True)),
                ('recommendation_for_hospital', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
