# Generated by Django 6.0.6 on 2026-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='ICU_OT',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='arrival_of_ambulance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='care_co_opp_of_administrator',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='doctor_response',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='hospital_sanitaion',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='if_yes_problem_solved_promptly_or_not',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='pharmacy',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='problem_during_stay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='promptness_of_service',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfaction_with_ambulance_internal_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfied_by_nurse_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfied_with_doctor_explanation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfied_with_overall_aspect_of_hospital',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='service_promptness_emegency_service',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='ward_cleanliness',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='x_ray_usg_echo_pathology_endoscopy_physio',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
    ]
