# Generated by Django 6.0.6 on 2026-06-09 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedbackform_bathroom_cleanliness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='ICU_OT',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='Signature',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='arrival_of_ambulance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='bathroom_cleanliness',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='everythin_clean_or_not',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='if_yes_problem_solved_promptly_or_not',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='pharmacy',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='problem_during_stay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='room_sanitation',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfaction_with_ambulance_internal_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='satisfied_with_overall_aspect_of_hospital',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='service_promptness_emegency_service',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='ward_cleanliness',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='would_you_share_or_not',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='x_ray_usg_echo_pathology_endoscopy_physio',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')]),
        ),
    ]
