# Generated by Django 6.0.6 on 2026-06-10 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_feedbackform_icu_ot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_alphabet', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')]),
        ),
    ]
