# Generated by Django 6.0.6 on 2026-06-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feedbackform_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='bed_no',
            field=models.CharField(max_length=5),
        ),
    ]
